knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Pagination Bootstrap 5
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Tri Bootstrap 5
